name: Lint and Build TS on PR

on: 
  pull_request:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Configure github
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        
        git remote -v
        git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
        git remote -v
    - name: Install node packages
      run: npm install
    - name: eLint
      run: |
        npm run elint
    - name: sLint
      run: |
        npm run slint
    - name: BUILD
      run: npm run build
