name: Deploy on PR

on: 
  push:
    branches:
        - staging
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Configure github
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        
        git remote -v
        git remote set-url origin git@github.com:${GITHUB_REPOSITORY}.git
        git remote -v
    - name: Install node packages
      run: npm install
    - name: eLint
      run: |
        npm run elint
    - name: sLint
      run: |
        npm run slint
    - name: BUILD
      run: npm run build
    - name: DEPLOY
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
      run: |
        SSH_DIR="${HOME}/.ssh"
        mkdir "${SSH_DIR}"
        ssh-keyscan -t rsa github.com > "${SSH_DIR}/known_hosts"
        echo "${ACTIONS_DEPLOY_KEY}" > "${SSH_DIR}/id_rsa"
        chmod 400 "${SSH_DIR}/id_rsa"
        git commit -am "Built latest version as a GH action"
        git subtree split --prefix build -b gh-pages
        git push -f origin gh-pages:gh-pages
